### ISSUE TITLE
tests for log-searcher

### ISSUE THREAD

**Issue by rohit-cribl** [prathmeshranaut/log-searcher#1]
Hello Prathmesh,

Will it be possible to add some tests for the primary functionality? You can focus on some basic functionality, input validations, edge cases etc.

**Comment by prathmeshranaut** [comment]
I've added some tests to test the exported methods of SearchController and the ValidationMiddleware. 

I did not add tests for the core buffer and file reading business logic. If would involve mocking `fs` and a lot of test. If you are looking for me to add that, let me know.
